recipe: default.v1

language: en

pipeline:
  - name: WhitespaceTokenizer
    intent_tokenization_flag: True
    intent_split_symbol: "+"
  - name: RegexFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: LexicalSyntacticFeaturizer
  - name: DIETClassifier
    epochs: 30
    constrain_similarities: True
    random_seed: 42
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 30
    retrieval_intent: chitchat
  - name: ResponseSelector
    epochs: 30
    retrieval_intent: faq
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.2

policies:
  - name: RulePolicy
    nlu_threhold: 0.4
    core_threshold: 0.4
    fallback_action_name: "action_default_fallback"
  - name: MemoizationPolicy
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 10
  - name: TEDPolicy
    max_history: 5
    epochs: 10
